### ISSUE TITLE
Provide a way for each fraction to add its own configuration

### ISSUE THREAD

**Issue by antoinesd** [swarmic/swarmic#10]
Some Fraction are based on existing CDI 1.0 code supposing a bean discovery in "all" mode. Since annotated mode is the best choice regarding performance and uber jar, we may allow fraction to add programmatically classes or package to type set.
This could be down at boot time by using a service provider approach to change container configuration before bootstrapping application

**Comment by johnament** [comment]
@antoinesd please when committing, use #ticketNo to reference a ticket.

**Comment by antoinesd** [comment]
That was the case twice in the commit message

> swarmic-**10** Bootstrap sequence enhancement providing config feature fo…
> …r fractions
> 
> Add a banner at boot time
> closes **#10**
>

**Comment by antoinesd** [comment]
But I agree it''s not very clear. Do you have suggestion for standard commit message format ?
