### ISSUE TITLE
Add CI support

### ISSUE THREAD

**Issue by antoinesd** [swarmic/swarmic#12]
What would you recommend @johnament ? Travis CI, Cirlce CI. I was using CloudBees 3 years ago but perhaps its outdated now ?

**Comment by johnament** [comment]
Jenkins is still great. I'm not sure their stance on FOSS accounts.  We actually had a lot of issues trying to get an account setup for Java EE samples.

Travis is good as well.  May be nice to start with something small and grow from here.

I've never tried CircleCI, but it seems like their target is to get you to buy.
