### ISSUE TITLE
Preload persistence units

### ISSUE THREAD

**Issue by johnament** [swarmic/swarmic#22]
Persistence units should be preloaded on app deploy, rather than waiting for the first action that uses it.  It slows down app start up, but gives you better errors when running an app.

**Comment by johnament** [comment]
Done.

**Comment by antoinesd** [comment]
Where is the commit @johnament ?

**Comment by johnament** [comment]
D'oh, wrong ticket :-)

**Comment by antoinesd** [comment]
Done & tested
