### ISSUE TITLE
Database transactions never complete

### ISSUE THREAD

**Issue by johnament** [swarmic/swarmic#26]
- Update the rest-jpa example so that it includes a simple insert operation:
```
    @POST
    @Consumes("text/plain")
    public Response create(String name) {
        Employee employee = new Employee(name);
        Employee result = service.create(employee);
        return Response.ok(result.getId()).build();
    }
```

The service:

```
    public Employee create(Employee employee) {
        return em.merge(employee);
    }
```

With a minor fix to Employee so that its an Integer instead of an int.  

- Run the app, trying to insert a row.
- See that it never performs the insert.

**Comment by antoinesd** [comment]
After testing, pb seems to come from example configuration: see swarmic/swarmic-examples#3

**Comment by johnament** [comment]
Non-issue.
