### ISSUE TITLE
Adding JTA support

### ISSUE THREAD

**Issue by antoinesd** [swarmic/swarmic#5]
To get transactional event and working `@Transaction` a JTA fraction should be added to swarmic.
The implementationobvious choice is probably Naranaya ;)

**Comment by johnament** [comment]
We should be careful here to figure out if we need JTA support, or if using JPA w/ resource local transactions is enough.

**Comment by antoinesd** [comment]
I think we should support both. JPA with resource local is sufficient for some use case, but if people want to use `@Transactional` interceptor included in JTA or have transactional event support we should provide it. Regarding the last one, we only have proprietary solutions to include this support...
